### ISSUE TITLE
Possible Data lifecycle diagram changes

### ISSUE THREAD

**Issue by RooyyDoe** [Jelmerovereem/real-time-web-2021#5]
- [x] Make the code comments bigger
- [x] Add all the events that you use
- [x] Give more explanation by the events/client/server
- [x] Show database table

IF you even need an example for a data lifecycle diagram you can take mine! 😃

**Comment by RooyyDoe** [comment]
Don't even know if you have it finished, but if you have I can look at it again just message me.

**Comment by Jelmerovereem** [comment]
d8de393
